/* generated from generate_instructions.py: l.6131 */

#include "instructions.gen.h"

const struct Instruction opcode_lookup_table[256] = {
    [0x00] = {
        .mnemonic = "NOP",
        .full_mnemonic = "NOP",
        .handler = nop,
        .length = 1,
        .cycles = 2,
    },
    [0x01] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 0",
        .handler = tcall_0,
        .length = 0,
        .cycles = 0,
    },
    [0x02] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x03] = {
        .mnemonic = "BBS",
        .full_mnemonic = "BBS d.0, r",
        .handler = bbs_0,
        .length = 1,
        .cycles = 4,
    },
    [0x04] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, d",
        .handler = or_register_direct_a,
        .length = 2,
        .cycles = 3,
    },
    [0x05] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, !a",
        .handler = or_register_absolute_a,
        .length = 3,
        .cycles = 4,
    },
    [0x06] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, (X)",
        .handler = or_register_indirect,
        .length = 1,
        .cycles = 3,
    },
    [0x07] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, [d+X]",
        .handler = or_register_indexed_indirect,
        .length = 2,
        .cycles = 6,
    },
    [0x08] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, #i",
        .handler = or_register_immediate_a,
        .length = 2,
        .cycles = 2,
    },
    [0x09] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    dd, ds",
        .handler = or_direct_direct,
        .length = 3,
        .cycles = 6,
    },
    [0x0a] = {
        .mnemonic = "OR1",
        .full_mnemonic = "OR1 C, m.b",
        .handler = or1,
        .length = 1,
        .cycles = 4,
    },
    [0x0b] = {
        .mnemonic = "ASL",
        .full_mnemonic = "ASL   d",
        .handler = asl_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x0c] = {
        .mnemonic = "ASL",
        .full_mnemonic = "ASL   !a",
        .handler = asl_absolute,
        .length = 3,
        .cycles = 5,
    },
    [0x0d] = {
        .mnemonic = "PUSH",
        .full_mnemonic = "PUSH  PSW",
        .handler = push_status,
        .length = 1,
        .cycles = 4,
    },
    [0x0e] = {
        .mnemonic = "TSET1",
        .full_mnemonic = "TSET1 !a",
        .handler = tset1,
        .length = 1,
        .cycles = 4,
    },
    [0x0f] = {
        .mnemonic = "BRK",
        .full_mnemonic = "BRK",
        .handler = brk,
        .length = 1,
        .cycles = 4,
    },
    [0x10] = {
        .mnemonic = "BPL",
        .full_mnemonic = "BPL",
        .handler = bpl,
        .length = 2,
        .cycles = 2,
    },
    [0x11] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 1",
        .handler = tcall_1,
        .length = 0,
        .cycles = 0,
    },
    [0x12] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x13] = {
        .mnemonic = "BBC",
        .full_mnemonic = "BBC d.0, r",
        .handler = bbc_0,
        .length = 1,
        .cycles = 4,
    },
    [0x14] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, d+X",
        .handler = or_register_direct_indexed_a_x,
        .length = 2,
        .cycles = 4,
    },
    [0x15] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, !a+X",
        .handler = or_register_absolute_indexed_x,
        .length = 3,
        .cycles = 5,
    },
    [0x16] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, !a+Y",
        .handler = or_register_absolute_indexed_y,
        .length = 3,
        .cycles = 5,
    },
    [0x17] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, [d]+Y",
        .handler = or_register_indirect_indexed,
        .length = 2,
        .cycles = 6,
    },
    [0x18] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    d, #i",
        .handler = or_direct_immediate,
        .length = 3,
        .cycles = 5,
    },
    [0x19] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    (X), (Y)",
        .handler = or_indirect_indirect,
        .length = 1,
        .cycles = 5,
    },
    [0x1a] = {
        .mnemonic = "DECW",
        .full_mnemonic = "DECW d",
        .handler = decw,
        .length = 1,
        .cycles = 4,
    },
    [0x1b] = {
        .mnemonic = "ASL",
        .full_mnemonic = "ASL   d+X",
        .handler = asl_direct_indexed,
        .length = 2,
        .cycles = 5,
    },
    [0x1c] = {
        .mnemonic = "ASL",
        .full_mnemonic = "ASL   A",
        .handler = asl_a,
        .length = 1,
        .cycles = 4,
    },
    [0x1d] = {
        .mnemonic = "DEC",
        .full_mnemonic = "DEC   X",
        .handler = dec_x,
        .length = 1,
        .cycles = 4,
    },
    [0x1e] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   X, !a",
        .handler = cmp_register_absolute_x,
        .length = 3,
        .cycles = 4,
    },
    [0x1f] = {
        .mnemonic = "JMP",
        .full_mnemonic = "JMP [!a+X]",
        .handler = jmp_abs_x_indirect,
        .length = 1,
        .cycles = 4,
    },
    [0x20] = {
        .mnemonic = "CLRP",
        .full_mnemonic = "CLRP",
        .handler = clrp,
        .length = 1,
        .cycles = 2,
    },
    [0x21] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 2",
        .handler = tcall_2,
        .length = 0,
        .cycles = 0,
    },
    [0x22] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_1_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x23] = {
        .mnemonic = "BBS",
        .full_mnemonic = "BBS d.1, r",
        .handler = bbs_1,
        .length = 1,
        .cycles = 4,
    },
    [0x24] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, d",
        .handler = and_register_direct_a,
        .length = 2,
        .cycles = 3,
    },
    [0x25] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, !a",
        .handler = and_register_absolute_a,
        .length = 3,
        .cycles = 4,
    },
    [0x26] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, (X)",
        .handler = and_register_indirect,
        .length = 1,
        .cycles = 3,
    },
    [0x27] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, [d+X]",
        .handler = and_register_indexed_indirect,
        .length = 2,
        .cycles = 6,
    },
    [0x28] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, #i",
        .handler = and_register_immediate_a,
        .length = 2,
        .cycles = 2,
    },
    [0x29] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   dd, ds",
        .handler = and_direct_direct,
        .length = 3,
        .cycles = 6,
    },
    [0x2a] = {
        .mnemonic = "OR1",
        .full_mnemonic = "OR1 C, /m.b",
        .handler = or1_not,
        .length = 1,
        .cycles = 4,
    },
    [0x2b] = {
        .mnemonic = "ROL",
        .full_mnemonic = "ROL   d",
        .handler = rol_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x2c] = {
        .mnemonic = "ROL",
        .full_mnemonic = "ROL   !a",
        .handler = rol_absolute,
        .length = 3,
        .cycles = 5,
    },
    [0x2d] = {
        .mnemonic = "PUSH",
        .full_mnemonic = "PUSH  A",
        .handler = push_a,
        .length = 1,
        .cycles = 4,
    },
    [0x2e] = {
        .mnemonic = "CBNE",
        .full_mnemonic = "CBNE d, r",
        .handler = cbne_dp,
        .length = 1,
        .cycles = 4,
    },
    [0x2f] = {
        .mnemonic = "BRA",
        .full_mnemonic = "BRA",
        .handler = bra,
        .length = 2,
        .cycles = 2,
    },
    [0x30] = {
        .mnemonic = "BMI",
        .full_mnemonic = "BMI",
        .handler = bmi,
        .length = 2,
        .cycles = 2,
    },
    [0x31] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 3",
        .handler = tcall_3,
        .length = 0,
        .cycles = 0,
    },
    [0x32] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_1_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x33] = {
        .mnemonic = "BBC",
        .full_mnemonic = "BBC d.1, r",
        .handler = bbc_1,
        .length = 1,
        .cycles = 4,
    },
    [0x34] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, d+X",
        .handler = and_register_direct_indexed_a_x,
        .length = 2,
        .cycles = 4,
    },
    [0x35] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, !a+X",
        .handler = and_register_absolute_indexed_x,
        .length = 3,
        .cycles = 5,
    },
    [0x36] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, !a+Y",
        .handler = and_register_absolute_indexed_y,
        .length = 3,
        .cycles = 5,
    },
    [0x37] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, [d]+Y",
        .handler = and_register_indirect_indexed,
        .length = 2,
        .cycles = 6,
    },
    [0x38] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   d, #i",
        .handler = and_direct_immediate,
        .length = 3,
        .cycles = 5,
    },
    [0x39] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   (X), (Y)",
        .handler = and_indirect_indirect,
        .length = 1,
        .cycles = 5,
    },
    [0x3a] = {
        .mnemonic = "INCW",
        .full_mnemonic = "INCW d",
        .handler = incw,
        .length = 1,
        .cycles = 4,
    },
    [0x3b] = {
        .mnemonic = "ROL",
        .full_mnemonic = "ROL   d+X",
        .handler = rol_direct_indexed,
        .length = 2,
        .cycles = 5,
    },
    [0x3c] = {
        .mnemonic = "ROL",
        .full_mnemonic = "ROL   A",
        .handler = rol_a,
        .length = 1,
        .cycles = 4,
    },
    [0x3d] = {
        .mnemonic = "INC",
        .full_mnemonic = "INC   X",
        .handler = inc_x,
        .length = 1,
        .cycles = 4,
    },
    [0x3e] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   X, d",
        .handler = cmp_register_direct_x,
        .length = 2,
        .cycles = 3,
    },
    [0x3f] = {
        .mnemonic = "CALL",
        .full_mnemonic = "CALL !a",
        .handler = call,
        .length = 1,
        .cycles = 4,
    },
    [0x40] = {
        .mnemonic = "SETP",
        .full_mnemonic = "SETP",
        .handler = setp,
        .length = 1,
        .cycles = 2,
    },
    [0x41] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 4",
        .handler = tcall_4,
        .length = 0,
        .cycles = 0,
    },
    [0x42] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_2_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x43] = {
        .mnemonic = "BBS",
        .full_mnemonic = "BBS d.2, r",
        .handler = bbs_2,
        .length = 1,
        .cycles = 4,
    },
    [0x44] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, d",
        .handler = eor_register_direct_a,
        .length = 2,
        .cycles = 3,
    },
    [0x45] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, !a",
        .handler = eor_register_absolute_a,
        .length = 3,
        .cycles = 4,
    },
    [0x46] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, (X)",
        .handler = eor_register_indirect,
        .length = 1,
        .cycles = 3,
    },
    [0x47] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, [d+X]",
        .handler = eor_register_indexed_indirect,
        .length = 2,
        .cycles = 6,
    },
    [0x48] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, #i",
        .handler = eor_register_immediate_a,
        .length = 2,
        .cycles = 2,
    },
    [0x49] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   dd, ds",
        .handler = eor_direct_direct,
        .length = 3,
        .cycles = 6,
    },
    [0x4a] = {
        .mnemonic = "AND1",
        .full_mnemonic = "AND1 C, m.b",
        .handler = and1,
        .length = 1,
        .cycles = 4,
    },
    [0x4b] = {
        .mnemonic = "LSR",
        .full_mnemonic = "LSR   d",
        .handler = lsr_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x4c] = {
        .mnemonic = "LSR",
        .full_mnemonic = "LSR   !a",
        .handler = lsr_absolute,
        .length = 3,
        .cycles = 5,
    },
    [0x4d] = {
        .mnemonic = "PUSH",
        .full_mnemonic = "PUSH  X",
        .handler = push_x,
        .length = 1,
        .cycles = 4,
    },
    [0x4e] = {
        .mnemonic = "TCLR1",
        .full_mnemonic = "TCLR1 !a",
        .handler = tclr1,
        .length = 1,
        .cycles = 4,
    },
    [0x4f] = {
        .mnemonic = "PCALL",
        .full_mnemonic = "PCALL u",
        .handler = pcall,
        .length = 1,
        .cycles = 4,
    },
    [0x50] = {
        .mnemonic = "BVC",
        .full_mnemonic = "BVC",
        .handler = bvc,
        .length = 2,
        .cycles = 2,
    },
    [0x51] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 5",
        .handler = tcall_5,
        .length = 0,
        .cycles = 0,
    },
    [0x52] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_2_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x53] = {
        .mnemonic = "BBC",
        .full_mnemonic = "BBC d.2, r",
        .handler = bbc_2,
        .length = 1,
        .cycles = 4,
    },
    [0x54] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, d+X",
        .handler = eor_register_direct_indexed_a_x,
        .length = 2,
        .cycles = 4,
    },
    [0x55] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, !a+X",
        .handler = eor_register_absolute_indexed_x,
        .length = 3,
        .cycles = 5,
    },
    [0x56] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, !a+Y",
        .handler = eor_register_absolute_indexed_y,
        .length = 3,
        .cycles = 5,
    },
    [0x57] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, [d]+Y",
        .handler = eor_register_indirect_indexed,
        .length = 2,
        .cycles = 6,
    },
    [0x58] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   d, #i",
        .handler = eor_direct_immediate,
        .length = 3,
        .cycles = 5,
    },
    [0x59] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   (X), (Y)",
        .handler = eor_indirect_indirect,
        .length = 1,
        .cycles = 5,
    },
    [0x5a] = {
        .mnemonic = "CMPW",
        .full_mnemonic = "CMPW YA, d",
        .handler = cmpw,
        .length = 1,
        .cycles = 4,
    },
    [0x5b] = {
        .mnemonic = "LSR",
        .full_mnemonic = "LSR   d+X",
        .handler = lsr_direct_indexed,
        .length = 2,
        .cycles = 5,
    },
    [0x5c] = {
        .mnemonic = "LSR",
        .full_mnemonic = "LSR   A",
        .handler = lsr_a,
        .length = 1,
        .cycles = 4,
    },
    [0x5d] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, A",
        .handler = mov_reg_reg_x_a,
        .length = 0,
        .cycles = 0,
    },
    [0x5e] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   Y, !a",
        .handler = cmp_register_absolute_y,
        .length = 3,
        .cycles = 4,
    },
    [0x5f] = {
        .mnemonic = "JMP",
        .full_mnemonic = "JMP !a",
        .handler = jmp_abs,
        .length = 1,
        .cycles = 4,
    },
    [0x60] = {
        .mnemonic = "CLRC",
        .full_mnemonic = "CLRC",
        .handler = clrc,
        .length = 1,
        .cycles = 2,
    },
    [0x61] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 6",
        .handler = tcall_6,
        .length = 0,
        .cycles = 0,
    },
    [0x62] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_3_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x63] = {
        .mnemonic = "BBS",
        .full_mnemonic = "BBS d.3, r",
        .handler = bbs_3,
        .length = 1,
        .cycles = 4,
    },
    [0x64] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, d",
        .handler = cmp_register_direct_a,
        .length = 2,
        .cycles = 3,
    },
    [0x65] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, !a",
        .handler = cmp_register_absolute_a,
        .length = 3,
        .cycles = 4,
    },
    [0x66] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, (X)",
        .handler = cmp_register_indirect,
        .length = 1,
        .cycles = 3,
    },
    [0x67] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, [d+X]",
        .handler = cmp_register_indexed_indirect,
        .length = 2,
        .cycles = 6,
    },
    [0x68] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, #i",
        .handler = cmp_register_immediate_a,
        .length = 2,
        .cycles = 2,
    },
    [0x69] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   dd, ds",
        .handler = cmp_direct_direct,
        .length = 3,
        .cycles = 6,
    },
    [0x6a] = {
        .mnemonic = "AND1",
        .full_mnemonic = "AND1 C, /m.b",
        .handler = and1_not,
        .length = 1,
        .cycles = 4,
    },
    [0x6b] = {
        .mnemonic = "ROR",
        .full_mnemonic = "ROR   d",
        .handler = ror_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x6c] = {
        .mnemonic = "ROR",
        .full_mnemonic = "ROR   !a",
        .handler = ror_absolute,
        .length = 3,
        .cycles = 5,
    },
    [0x6d] = {
        .mnemonic = "PUSH",
        .full_mnemonic = "PUSH  Y",
        .handler = push_y,
        .length = 1,
        .cycles = 4,
    },
    [0x6e] = {
        .mnemonic = "DBNZ",
        .full_mnemonic = "DBNZ d, r",
        .handler = dbnz_dp,
        .length = 1,
        .cycles = 4,
    },
    [0x6f] = {
        .mnemonic = "RET",
        .full_mnemonic = "RET",
        .handler = ret,
        .length = 1,
        .cycles = 4,
    },
    [0x70] = {
        .mnemonic = "BVS",
        .full_mnemonic = "BVS",
        .handler = bvs,
        .length = 2,
        .cycles = 2,
    },
    [0x71] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 7",
        .handler = tcall_7,
        .length = 0,
        .cycles = 0,
    },
    [0x72] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_3_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x73] = {
        .mnemonic = "BBC",
        .full_mnemonic = "BBC d.3, r",
        .handler = bbc_3,
        .length = 1,
        .cycles = 4,
    },
    [0x74] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, d+X",
        .handler = cmp_register_direct_indexed_a_x,
        .length = 2,
        .cycles = 4,
    },
    [0x75] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, !a+X",
        .handler = cmp_register_absolute_indexed_x,
        .length = 3,
        .cycles = 5,
    },
    [0x76] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, !a+Y",
        .handler = cmp_register_absolute_indexed_y,
        .length = 3,
        .cycles = 5,
    },
    [0x77] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, [d]+Y",
        .handler = cmp_register_indirect_indexed,
        .length = 2,
        .cycles = 6,
    },
    [0x78] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   d, #i",
        .handler = cmp_direct_immediate,
        .length = 3,
        .cycles = 5,
    },
    [0x79] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   (X), (Y)",
        .handler = cmp_indirect_indirect,
        .length = 1,
        .cycles = 5,
    },
    [0x7a] = {
        .mnemonic = "ADDW",
        .full_mnemonic = "ADDW YA, d",
        .handler = addw,
        .length = 1,
        .cycles = 4,
    },
    [0x7b] = {
        .mnemonic = "ROR",
        .full_mnemonic = "ROR   d+X",
        .handler = ror_direct_indexed,
        .length = 2,
        .cycles = 5,
    },
    [0x7c] = {
        .mnemonic = "ROR",
        .full_mnemonic = "ROR   A",
        .handler = ror_a,
        .length = 1,
        .cycles = 4,
    },
    [0x7d] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, X",
        .handler = mov_reg_reg_a_x,
        .length = 0,
        .cycles = 0,
    },
    [0x7e] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP Y, d",
        .handler = cmp_y_dp,
        .length = 1,
        .cycles = 4,
    },
    [0x7f] = {
        .mnemonic = "RET1",
        .full_mnemonic = "RET1",
        .handler = ret1,
        .length = 1,
        .cycles = 4,
    },
    [0x80] = {
        .mnemonic = "SETC",
        .full_mnemonic = "SETC",
        .handler = setc,
        .length = 1,
        .cycles = 2,
    },
    [0x81] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 8",
        .handler = tcall_8,
        .length = 0,
        .cycles = 0,
    },
    [0x82] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_4_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x83] = {
        .mnemonic = "BBS",
        .full_mnemonic = "BBS d.4, r",
        .handler = bbs_4,
        .length = 1,
        .cycles = 4,
    },
    [0x84] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, d",
        .handler = adc_register_direct_a,
        .length = 2,
        .cycles = 3,
    },
    [0x85] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, !a",
        .handler = adc_register_absolute_a,
        .length = 3,
        .cycles = 4,
    },
    [0x86] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, (X)",
        .handler = adc_register_indirect,
        .length = 1,
        .cycles = 3,
    },
    [0x87] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, [d+X]",
        .handler = adc_register_indexed_indirect,
        .length = 2,
        .cycles = 6,
    },
    [0x88] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, #i",
        .handler = adc_register_immediate_a,
        .length = 2,
        .cycles = 2,
    },
    [0x89] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   dd, ds",
        .handler = adc_direct_direct,
        .length = 3,
        .cycles = 6,
    },
    [0x8a] = {
        .mnemonic = "EOR1",
        .full_mnemonic = "EOR1 C, m.b",
        .handler = eor1,
        .length = 1,
        .cycles = 4,
    },
    [0x8b] = {
        .mnemonic = "DEC",
        .full_mnemonic = "DEC   d",
        .handler = dec_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x8c] = {
        .mnemonic = "DEC",
        .full_mnemonic = "DEC   !a",
        .handler = dec_absolute,
        .length = 3,
        .cycles = 5,
    },
    [0x8d] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   Y, #i",
        .handler = mov_register_immediate_y,
        .length = 2,
        .cycles = 2,
    },
    [0x8e] = {
        .mnemonic = "POP",
        .full_mnemonic = "POP   PSW",
        .handler = pop_status,
        .length = 1,
        .cycles = 4,
    },
    [0x8f] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d, #i",
        .handler = mov_direct_immediate,
        .length = 3,
        .cycles = 5,
    },
    [0x90] = {
        .mnemonic = "BCC",
        .full_mnemonic = "BCC",
        .handler = bcc,
        .length = 2,
        .cycles = 2,
    },
    [0x91] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 9",
        .handler = tcall_9,
        .length = 0,
        .cycles = 0,
    },
    [0x92] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_4_direct,
        .length = 2,
        .cycles = 4,
    },
    [0x93] = {
        .mnemonic = "BBC",
        .full_mnemonic = "BBC d.4, r",
        .handler = bbc_4,
        .length = 1,
        .cycles = 4,
    },
    [0x94] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, d+X",
        .handler = adc_register_direct_indexed_a_x,
        .length = 2,
        .cycles = 4,
    },
    [0x95] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, !a+X",
        .handler = adc_register_absolute_indexed_x,
        .length = 3,
        .cycles = 5,
    },
    [0x96] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, !a+Y",
        .handler = adc_register_absolute_indexed_y,
        .length = 3,
        .cycles = 5,
    },
    [0x97] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, [d]+Y",
        .handler = adc_register_indirect_indexed,
        .length = 2,
        .cycles = 6,
    },
    [0x98] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   d, #i",
        .handler = adc_direct_immediate,
        .length = 3,
        .cycles = 5,
    },
    [0x99] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   (X), (Y)",
        .handler = adc_indirect_indirect,
        .length = 1,
        .cycles = 5,
    },
    [0x9a] = {
        .mnemonic = "SUBW",
        .full_mnemonic = "SUBW YA, d",
        .handler = subw,
        .length = 1,
        .cycles = 4,
    },
    [0x9b] = {
        .mnemonic = "DEC",
        .full_mnemonic = "DEC   d+X",
        .handler = dec_direct_indexed,
        .length = 2,
        .cycles = 5,
    },
    [0x9c] = {
        .mnemonic = "DEC",
        .full_mnemonic = "DEC   A",
        .handler = dec_a,
        .length = 1,
        .cycles = 4,
    },
    [0x9d] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, SP",
        .handler = mov_reg_reg_x_sp,
        .length = 0,
        .cycles = 0,
    },
    [0x9e] = {
        .mnemonic = "DIV",
        .full_mnemonic = "DIV YA, X",
        .handler = div_ya_x,
        .length = 1,
        .cycles = 4,
    },
    [0x9f] = {
        .mnemonic = "XCN",
        .full_mnemonic = "XCN A",
        .handler = xcn,
        .length = 1,
        .cycles = 4,
    },
    [0xa0] = {
        .mnemonic = "EI",
        .full_mnemonic = "EI",
        .handler = ei,
        .length = 1,
        .cycles = 3,
    },
    [0xa1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 10",
        .handler = tcall_10,
        .length = 0,
        .cycles = 0,
    },
    [0xa2] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_5_direct,
        .length = 2,
        .cycles = 4,
    },
    [0xa3] = {
        .mnemonic = "BBS",
        .full_mnemonic = "BBS d.5, r",
        .handler = bbs_5,
        .length = 1,
        .cycles = 4,
    },
    [0xa4] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, d",
        .handler = sbc_register_direct_a,
        .length = 2,
        .cycles = 3,
    },
    [0xa5] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, !a",
        .handler = sbc_register_absolute_a,
        .length = 3,
        .cycles = 4,
    },
    [0xa6] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, (X)",
        .handler = sbc_register_indirect,
        .length = 1,
        .cycles = 3,
    },
    [0xa7] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, [d+X]",
        .handler = sbc_register_indexed_indirect,
        .length = 2,
        .cycles = 6,
    },
    [0xa8] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, #i",
        .handler = sbc_register_immediate_a,
        .length = 2,
        .cycles = 2,
    },
    [0xa9] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   dd, ds",
        .handler = sbc_direct_direct,
        .length = 3,
        .cycles = 6,
    },
    [0xaa] = {
        .mnemonic = "MOV1",
        .full_mnemonic = "MOV1 C, m.b",
        .handler = mov1_c_membit,
        .length = 1,
        .cycles = 4,
    },
    [0xab] = {
        .mnemonic = "INC",
        .full_mnemonic = "INC   d",
        .handler = inc_direct,
        .length = 2,
        .cycles = 4,
    },
    [0xac] = {
        .mnemonic = "INC",
        .full_mnemonic = "INC   !a",
        .handler = inc_absolute,
        .length = 3,
        .cycles = 5,
    },
    [0xad] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   Y, #i",
        .handler = cmp_register_immediate_y,
        .length = 2,
        .cycles = 2,
    },
    [0xae] = {
        .mnemonic = "POP",
        .full_mnemonic = "POP   A",
        .handler = pop_a,
        .length = 1,
        .cycles = 4,
    },
    [0xaf] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   (X)+, A",
        .handler = mov_indirect_incremented_register,
        .length = 1,
        .cycles = 4,
    },
    [0xb0] = {
        .mnemonic = "BCS",
        .full_mnemonic = "BCS",
        .handler = bcs,
        .length = 2,
        .cycles = 2,
    },
    [0xb1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 11",
        .handler = tcall_11,
        .length = 0,
        .cycles = 0,
    },
    [0xb2] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_5_direct,
        .length = 2,
        .cycles = 4,
    },
    [0xb3] = {
        .mnemonic = "BBC",
        .full_mnemonic = "BBC d.5, r",
        .handler = bbc_5,
        .length = 1,
        .cycles = 4,
    },
    [0xb4] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, d+X",
        .handler = sbc_register_direct_indexed_a_x,
        .length = 2,
        .cycles = 4,
    },
    [0xb5] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, !a+X",
        .handler = sbc_register_absolute_indexed_x,
        .length = 3,
        .cycles = 5,
    },
    [0xb6] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, !a+Y",
        .handler = sbc_register_absolute_indexed_y,
        .length = 3,
        .cycles = 5,
    },
    [0xb7] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, [d]+Y",
        .handler = sbc_register_indirect_indexed,
        .length = 2,
        .cycles = 6,
    },
    [0xb8] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   d, #i",
        .handler = sbc_direct_immediate,
        .length = 3,
        .cycles = 5,
    },
    [0xb9] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   (X), (Y)",
        .handler = sbc_indirect_indirect,
        .length = 1,
        .cycles = 5,
    },
    [0xba] = {
        .mnemonic = "MOVW",
        .full_mnemonic = "MOVW YA, d",
        .handler = movw_ya_dp,
        .length = 1,
        .cycles = 4,
    },
    [0xbb] = {
        .mnemonic = "INC",
        .full_mnemonic = "INC   d+X",
        .handler = inc_direct_indexed,
        .length = 2,
        .cycles = 5,
    },
    [0xbc] = {
        .mnemonic = "INC",
        .full_mnemonic = "INC   A",
        .handler = inc_a,
        .length = 1,
        .cycles = 4,
    },
    [0xbd] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   SP, X",
        .handler = mov_reg_reg_sp_x,
        .length = 0,
        .cycles = 0,
    },
    [0xbe] = {
        .mnemonic = "DAS",
        .full_mnemonic = "DAS A",
        .handler = das,
        .length = 1,
        .cycles = 4,
    },
    [0xbf] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, (X)+",
        .handler = mov_register_indirect_incremented,
        .length = 1,
        .cycles = 4,
    },
    [0xc0] = {
        .mnemonic = "DI",
        .full_mnemonic = "DI",
        .handler = di,
        .length = 1,
        .cycles = 3,
    },
    [0xc1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 12",
        .handler = tcall_12,
        .length = 0,
        .cycles = 0,
    },
    [0xc2] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_6_direct,
        .length = 2,
        .cycles = 4,
    },
    [0xc3] = {
        .mnemonic = "BBS",
        .full_mnemonic = "BBS d.6, r",
        .handler = bbs_6,
        .length = 1,
        .cycles = 4,
    },
    [0xc4] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d, a",
        .handler = mov_direct_register_a,
        .length = 2,
        .cycles = 4,
    },
    [0xc5] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   !a, a",
        .handler = mov_absolute_a,
        .length = 1,
        .cycles = 4,
    },
    [0xc6] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   (X), A",
        .handler = mov_indirect_register,
        .length = 1,
        .cycles = 4,
    },
    [0xc7] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   [d+X],A",
        .handler = mov_indexed_indirect_register,
        .length = 1,
        .cycles = 4,
    },
    [0xc8] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   X, #i",
        .handler = cmp_register_immediate_x,
        .length = 2,
        .cycles = 2,
    },
    [0xc9] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   !a, x",
        .handler = mov_absolute_x,
        .length = 1,
        .cycles = 4,
    },
    [0xca] = {
        .mnemonic = "MOV1",
        .full_mnemonic = "MOV1 m.b, C",
        .handler = mov1_membit_c,
        .length = 1,
        .cycles = 4,
    },
    [0xcb] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d, y",
        .handler = mov_direct_register_y,
        .length = 2,
        .cycles = 4,
    },
    [0xcc] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   !a, y",
        .handler = mov_absolute_y,
        .length = 1,
        .cycles = 4,
    },
    [0xcd] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, #i",
        .handler = mov_register_immediate_x,
        .length = 2,
        .cycles = 2,
    },
    [0xce] = {
        .mnemonic = "POP",
        .full_mnemonic = "POP   X",
        .handler = pop_x,
        .length = 1,
        .cycles = 4,
    },
    [0xcf] = {
        .mnemonic = "MUL",
        .full_mnemonic = "MUL YA",
        .handler = mul,
        .length = 1,
        .cycles = 4,
    },
    [0xd0] = {
        .mnemonic = "BNE",
        .full_mnemonic = "BNE",
        .handler = bne,
        .length = 2,
        .cycles = 2,
    },
    [0xd1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 13",
        .handler = tcall_13,
        .length = 0,
        .cycles = 0,
    },
    [0xd2] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_6_direct,
        .length = 2,
        .cycles = 4,
    },
    [0xd3] = {
        .mnemonic = "BBC",
        .full_mnemonic = "BBC d.6, r",
        .handler = bbc_6,
        .length = 1,
        .cycles = 4,
    },
    [0xd4] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d+x, a",
        .handler = mov_direct_indexed_register_x_a,
        .length = 2,
        .cycles = 5,
    },
    [0xd5] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   !a+x, A",
        .handler = mov_absolute_indexed_x,
        .length = 1,
        .cycles = 4,
    },
    [0xd6] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   !a+y, A",
        .handler = mov_absolute_indexed_y,
        .length = 1,
        .cycles = 4,
    },
    [0xd7] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   [d]+Y,A",
        .handler = mov_indirect_indexed_register,
        .length = 1,
        .cycles = 4,
    },
    [0xd8] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d, x",
        .handler = mov_direct_register_x,
        .length = 2,
        .cycles = 4,
    },
    [0xd9] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d+y, x",
        .handler = mov_direct_indexed_register_y_x,
        .length = 2,
        .cycles = 5,
    },
    [0xda] = {
        .mnemonic = "MOVW",
        .full_mnemonic = "MOVW d, YA",
        .handler = movw_dp_ya,
        .length = 1,
        .cycles = 4,
    },
    [0xdb] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d+x, y",
        .handler = mov_direct_indexed_register_x_y,
        .length = 2,
        .cycles = 5,
    },
    [0xdc] = {
        .mnemonic = "DEC",
        .full_mnemonic = "DEC   Y",
        .handler = dec_y,
        .length = 1,
        .cycles = 4,
    },
    [0xdd] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, Y",
        .handler = mov_reg_reg_a_y,
        .length = 0,
        .cycles = 0,
    },
    [0xde] = {
        .mnemonic = "CBNE",
        .full_mnemonic = "CBNE d+X, r",
        .handler = cbne_dp_x,
        .length = 1,
        .cycles = 4,
    },
    [0xdf] = {
        .mnemonic = "DAA",
        .full_mnemonic = "DAA A",
        .handler = daa,
        .length = 1,
        .cycles = 4,
    },
    [0xe0] = {
        .mnemonic = "CLRV",
        .full_mnemonic = "CLRV",
        .handler = clrv,
        .length = 1,
        .cycles = 2,
    },
    [0xe1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 14",
        .handler = tcall_14,
        .length = 0,
        .cycles = 0,
    },
    [0xe2] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_7_direct,
        .length = 2,
        .cycles = 4,
    },
    [0xe3] = {
        .mnemonic = "BBS",
        .full_mnemonic = "BBS d.7, r",
        .handler = bbs_7,
        .length = 1,
        .cycles = 4,
    },
    [0xe4] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, d",
        .handler = mov_register_direct_a,
        .length = 2,
        .cycles = 3,
    },
    [0xe5] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, !a",
        .handler = mov_register_absolute_a,
        .length = 3,
        .cycles = 4,
    },
    [0xe6] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, (X)",
        .handler = mov_register_indirect,
        .length = 1,
        .cycles = 3,
    },
    [0xe7] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, [d+X]",
        .handler = mov_register_indexed_indirect,
        .length = 2,
        .cycles = 6,
    },
    [0xe8] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, #i",
        .handler = mov_register_immediate_a,
        .length = 2,
        .cycles = 2,
    },
    [0xe9] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, !a",
        .handler = mov_register_absolute_x,
        .length = 3,
        .cycles = 4,
    },
    [0xea] = {
        .mnemonic = "NOT1",
        .full_mnemonic = "NOT1  m.b",
        .handler = not1,
        .length = 1,
        .cycles = 4,
    },
    [0xeb] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   Y, d",
        .handler = mov_register_direct_y,
        .length = 2,
        .cycles = 3,
    },
    [0xec] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   Y, !a",
        .handler = mov_register_absolute_y,
        .length = 3,
        .cycles = 4,
    },
    [0xed] = {
        .mnemonic = "NOTC",
        .full_mnemonic = "NOTC",
        .handler = notc,
        .length = 1,
        .cycles = 4,
    },
    [0xee] = {
        .mnemonic = "POP",
        .full_mnemonic = "POP   Y",
        .handler = pop_y,
        .length = 1,
        .cycles = 4,
    },
    [0xef] = {
        .mnemonic = "SLEEP",
        .full_mnemonic = "SLEEP",
        .handler = sleep_,
        .length = 1,
        .cycles = 4,
    },
    [0xf0] = {
        .mnemonic = "BEQ",
        .full_mnemonic = "BEQ",
        .handler = beq,
        .length = 2,
        .cycles = 2,
    },
    [0xf1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 15",
        .handler = tcall_15,
        .length = 0,
        .cycles = 0,
    },
    [0xf2] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_7_direct,
        .length = 2,
        .cycles = 4,
    },
    [0xf3] = {
        .mnemonic = "BBC",
        .full_mnemonic = "BBC d.7, r",
        .handler = bbc_7,
        .length = 1,
        .cycles = 4,
    },
    [0xf4] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, d+X",
        .handler = mov_register_direct_indexed_a_x,
        .length = 2,
        .cycles = 4,
    },
    [0xf5] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, !a+X",
        .handler = mov_register_absolute_indexed_x,
        .length = 3,
        .cycles = 5,
    },
    [0xf6] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, !a+Y",
        .handler = mov_register_absolute_indexed_y,
        .length = 3,
        .cycles = 5,
    },
    [0xf7] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, [d]+Y",
        .handler = mov_register_indirect_indexed,
        .length = 2,
        .cycles = 6,
    },
    [0xf8] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, d",
        .handler = mov_register_direct_x,
        .length = 2,
        .cycles = 3,
    },
    [0xf9] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, d+Y",
        .handler = mov_register_direct_indexed_x_y,
        .length = 2,
        .cycles = 4,
    },
    [0xfa] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   dd, ds",
        .handler = mov_direct_direct,
        .length = 1,
        .cycles = 4,
    },
    [0xfb] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   Y, d+X",
        .handler = mov_register_direct_indexed_y_x,
        .length = 2,
        .cycles = 4,
    },
    [0xfc] = {
        .mnemonic = "INC",
        .full_mnemonic = "INC   Y",
        .handler = inc_y,
        .length = 1,
        .cycles = 4,
    },
    [0xfd] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   Y, A",
        .handler = mov_reg_reg_y_a,
        .length = 0,
        .cycles = 0,
    },
    [0xfe] = {
        .mnemonic = "DBNZ",
        .full_mnemonic = "DBNZ Y, r",
        .handler = dbnz_y,
        .length = 1,
        .cycles = 4,
    },
    [0xff] = {
        .mnemonic = "STOP",
        .full_mnemonic = "STOP",
        .handler = stop,
        .length = 1,
        .cycles = 4,
    },
};
