#include "instruction.h"

#include <stddef.h>

const struct Instruction opcode_lookup_table[256] = {
    [0x00] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x10] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x20] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x30] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x40] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x50] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x60] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x70] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x80] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x90] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xA0] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xB0] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xC0] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xD0] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xE0] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xF0] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x01] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x11] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x21] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x31] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x41] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x51] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x61] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x71] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x81] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x91] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xA1] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xB1] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xC1] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xD1] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xE1] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xF1] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x02] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x12] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x22] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x32] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x42] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x52] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x62] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x72] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x82] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x92] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xA2] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xB2] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xC2] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xD2] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xE2] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xF2] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x03] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x13] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x23] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x33] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x43] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x53] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x63] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x73] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x83] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x93] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xA3] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xB3] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xC3] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xD3] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xE3] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xF3] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x04] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x14] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x24] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x34] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x44] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x54] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x64] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x74] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x84] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x94] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xA4] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xB4] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xC4] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xD4] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xE4] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xF4] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x05] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x15] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x25] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x35] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x45] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x55] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x65] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x75] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x85] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x95] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xA5] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xB5] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xC5] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xD5] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xE5] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xF5] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x06] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x16] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x26] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x36] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x46] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x56] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x66] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x76] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x86] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x96] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xA6] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xB6] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xC6] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xD6] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xE6] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xF6] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x07] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x17] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x27] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x37] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x47] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x57] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x67] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x77] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x87] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x97] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xA7] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xB7] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xC7] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xD7] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xE7] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xF7] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x08] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x18] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x28] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x38] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x48] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x58] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x68] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x78] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x88] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x98] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xA8] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xB8] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xC8] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xD8] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xE8] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xF8] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x09] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x19] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x29] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x39] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x49] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x59] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x69] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x79] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x89] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x99] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xA9] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xB9] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xC9] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xD9] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xE9] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xF9] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x0A] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x1A] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x2A] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x3A] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x4A] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x5A] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x6A] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x7A] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x8A] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x9A] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xAA] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xBA] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xCA] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xDA] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xEA] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xFA] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x0B] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x1B] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x2B] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x3B] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x4B] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x5B] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x6B] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x7B] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x8B] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x9B] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xAB] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xBB] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xCB] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xDB] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xEB] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xFB] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x0C] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x1C] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x2C] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x3C] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x4C] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x5C] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x6C] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x7C] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x8C] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x9C] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xAC] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xBC] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xCC] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xDC] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xEC] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xFC] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x0D] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x1D] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x2D] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x3D] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x4D] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x5D] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x6D] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x7D] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x8D] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x9D] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xAD] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xBD] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xCD] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xDD] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xED] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xFD] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x0E] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x1E] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x2E] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x3E] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x4E] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x5E] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x6E] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x7E] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x8E] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x9E] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xAE] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xBE] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xCE] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xDE] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xEE] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xFE] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x0F] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x1F] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x2F] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x3F] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x4F] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x5F] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x6F] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x7F] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x8F] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0x9F] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xAF] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xBF] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xCF] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xDF] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xEF] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
    [0xFF] = {.mnemonic = "XXX",
              .addr_mode = -1,
              .handler = NULL,
              .length = 0,
              .cycles = 0},
};
