/* generated from generate_instructions.py: l.3550 */

#include "instructions.gen.h"

const struct Instruction opcode_lookup_table[256] = {
    [0x00] = {
        .mnemonic = "NOP",
        .full_mnemonic = "NOP",
        .handler = nop,
        .length = 0,
        .cycles = 0,
    },
    [0x01] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 0",
        .handler = tcall_0,
        .length = 0,
        .cycles = 0,
    },
    [0x02] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x03] = {0},
    [0x04] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, d",
        .handler = or_register_direct_a,
        .length = 0,
        .cycles = 0,
    },
    [0x05] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, !a",
        .handler = or_register_absolute_a,
        .length = 0,
        .cycles = 0,
    },
    [0x06] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, (X)",
        .handler = or_register_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x07] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, [d+X]",
        .handler = or_register_indexed_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x08] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, #i",
        .handler = or_register_immediate_a,
        .length = 0,
        .cycles = 0,
    },
    [0x09] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    dd, ds",
        .handler = or_direct_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x0a] = {0},
    [0x0b] = {
        .mnemonic = "ASL",
        .full_mnemonic = "ASL   d",
        .handler = asl_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x0c] = {0},
    [0x0d] = {0},
    [0x0e] = {0},
    [0x0f] = {0},
    [0x10] = {0},
    [0x11] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 1",
        .handler = tcall_1,
        .length = 0,
        .cycles = 0,
    },
    [0x12] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x13] = {0},
    [0x14] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, d+X",
        .handler = or_register_direct_indexed_a_x,
        .length = 0,
        .cycles = 0,
    },
    [0x15] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, !a+X",
        .handler = or_register_absolute_indexed_x,
        .length = 0,
        .cycles = 0,
    },
    [0x16] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, !a+Y",
        .handler = or_register_absolute_indexed_y,
        .length = 0,
        .cycles = 0,
    },
    [0x17] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    A, [d]+Y",
        .handler = or_register_indirect_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0x18] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    d, #i",
        .handler = or_direct_immediate,
        .length = 0,
        .cycles = 0,
    },
    [0x19] = {
        .mnemonic = "OR",
        .full_mnemonic = "OR    (X), (Y)",
        .handler = or_indirect_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x1a] = {0},
    [0x1b] = {
        .mnemonic = "ASL",
        .full_mnemonic = "ASL   d+X",
        .handler = asl_direct_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0x1c] = {0},
    [0x1d] = {0},
    [0x1e] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   X, !a",
        .handler = cmp_register_absolute_x,
        .length = 0,
        .cycles = 0,
    },
    [0x1f] = {0},
    [0x20] = {
        .mnemonic = "CLRP",
        .full_mnemonic = "CLRP",
        .handler = clrp,
        .length = 0,
        .cycles = 0,
    },
    [0x21] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 2",
        .handler = tcall_2,
        .length = 0,
        .cycles = 0,
    },
    [0x22] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_1_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x23] = {0},
    [0x24] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, d",
        .handler = and_register_direct_a,
        .length = 0,
        .cycles = 0,
    },
    [0x25] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, !a",
        .handler = and_register_absolute_a,
        .length = 0,
        .cycles = 0,
    },
    [0x26] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, (X)",
        .handler = and_register_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x27] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, [d+X]",
        .handler = and_register_indexed_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x28] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, #i",
        .handler = and_register_immediate_a,
        .length = 0,
        .cycles = 0,
    },
    [0x29] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   dd, ds",
        .handler = and_direct_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x2a] = {0},
    [0x2b] = {
        .mnemonic = "ROL",
        .full_mnemonic = "ROL   d",
        .handler = rol_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x2c] = {0},
    [0x2d] = {0},
    [0x2e] = {0},
    [0x2f] = {0},
    [0x30] = {0},
    [0x31] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 3",
        .handler = tcall_3,
        .length = 0,
        .cycles = 0,
    },
    [0x32] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_1_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x33] = {0},
    [0x34] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, d+X",
        .handler = and_register_direct_indexed_a_x,
        .length = 0,
        .cycles = 0,
    },
    [0x35] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, !a+X",
        .handler = and_register_absolute_indexed_x,
        .length = 0,
        .cycles = 0,
    },
    [0x36] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, !a+Y",
        .handler = and_register_absolute_indexed_y,
        .length = 0,
        .cycles = 0,
    },
    [0x37] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   A, [d]+Y",
        .handler = and_register_indirect_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0x38] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   d, #i",
        .handler = and_direct_immediate,
        .length = 0,
        .cycles = 0,
    },
    [0x39] = {
        .mnemonic = "AND",
        .full_mnemonic = "AND   (X), (Y)",
        .handler = and_indirect_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x3a] = {0},
    [0x3b] = {
        .mnemonic = "ROL",
        .full_mnemonic = "ROL   d+X",
        .handler = rol_direct_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0x3c] = {0},
    [0x3d] = {0},
    [0x3e] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   X, d",
        .handler = cmp_register_direct_x,
        .length = 0,
        .cycles = 0,
    },
    [0x3f] = {0},
    [0x40] = {
        .mnemonic = "SETP",
        .full_mnemonic = "SETP",
        .handler = setp,
        .length = 0,
        .cycles = 0,
    },
    [0x41] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 4",
        .handler = tcall_4,
        .length = 0,
        .cycles = 0,
    },
    [0x42] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_2_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x43] = {0},
    [0x44] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, d",
        .handler = eor_register_direct_a,
        .length = 0,
        .cycles = 0,
    },
    [0x45] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, !a",
        .handler = eor_register_absolute_a,
        .length = 0,
        .cycles = 0,
    },
    [0x46] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, (X)",
        .handler = eor_register_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x47] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, [d+X]",
        .handler = eor_register_indexed_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x48] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, #i",
        .handler = eor_register_immediate_a,
        .length = 0,
        .cycles = 0,
    },
    [0x49] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   dd, ds",
        .handler = eor_direct_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x4a] = {0},
    [0x4b] = {
        .mnemonic = "LSR",
        .full_mnemonic = "LSR   d",
        .handler = lsr_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x4c] = {0},
    [0x4d] = {0},
    [0x4e] = {0},
    [0x4f] = {0},
    [0x50] = {0},
    [0x51] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 5",
        .handler = tcall_5,
        .length = 0,
        .cycles = 0,
    },
    [0x52] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_2_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x53] = {0},
    [0x54] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, d+X",
        .handler = eor_register_direct_indexed_a_x,
        .length = 0,
        .cycles = 0,
    },
    [0x55] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, !a+X",
        .handler = eor_register_absolute_indexed_x,
        .length = 0,
        .cycles = 0,
    },
    [0x56] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, !a+Y",
        .handler = eor_register_absolute_indexed_y,
        .length = 0,
        .cycles = 0,
    },
    [0x57] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   A, [d]+Y",
        .handler = eor_register_indirect_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0x58] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   d, #i",
        .handler = eor_direct_immediate,
        .length = 0,
        .cycles = 0,
    },
    [0x59] = {
        .mnemonic = "EOR",
        .full_mnemonic = "EOR   (X), (Y)",
        .handler = eor_indirect_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x5a] = {0},
    [0x5b] = {
        .mnemonic = "LSR",
        .full_mnemonic = "LSR   d+X",
        .handler = lsr_direct_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0x5c] = {0},
    [0x5d] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, A",
        .handler = mov_reg_reg_x_a,
        .length = 0,
        .cycles = 0,
    },
    [0x5e] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   Y, !a",
        .handler = cmp_register_absolute_y,
        .length = 0,
        .cycles = 0,
    },
    [0x5f] = {0},
    [0x60] = {
        .mnemonic = "CLRC",
        .full_mnemonic = "CLRC",
        .handler = clrc,
        .length = 0,
        .cycles = 0,
    },
    [0x61] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 6",
        .handler = tcall_6,
        .length = 0,
        .cycles = 0,
    },
    [0x62] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_3_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x63] = {0},
    [0x64] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, d",
        .handler = cmp_register_direct_a,
        .length = 0,
        .cycles = 0,
    },
    [0x65] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, !a",
        .handler = cmp_register_absolute_a,
        .length = 0,
        .cycles = 0,
    },
    [0x66] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, (X)",
        .handler = cmp_register_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x67] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, [d+X]",
        .handler = cmp_register_indexed_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x68] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, #i",
        .handler = cmp_register_immediate_a,
        .length = 0,
        .cycles = 0,
    },
    [0x69] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   dd, ds",
        .handler = cmp_direct_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x6a] = {0},
    [0x6b] = {
        .mnemonic = "ROR",
        .full_mnemonic = "ROR   d",
        .handler = ror_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x6c] = {0},
    [0x6d] = {0},
    [0x6e] = {0},
    [0x6f] = {0},
    [0x70] = {0},
    [0x71] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 7",
        .handler = tcall_7,
        .length = 0,
        .cycles = 0,
    },
    [0x72] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_3_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x73] = {0},
    [0x74] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, d+X",
        .handler = cmp_register_direct_indexed_a_x,
        .length = 0,
        .cycles = 0,
    },
    [0x75] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, !a+X",
        .handler = cmp_register_absolute_indexed_x,
        .length = 0,
        .cycles = 0,
    },
    [0x76] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, !a+Y",
        .handler = cmp_register_absolute_indexed_y,
        .length = 0,
        .cycles = 0,
    },
    [0x77] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   A, [d]+Y",
        .handler = cmp_register_indirect_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0x78] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   d, #i",
        .handler = cmp_direct_immediate,
        .length = 0,
        .cycles = 0,
    },
    [0x79] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   (X), (Y)",
        .handler = cmp_indirect_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x7a] = {0},
    [0x7b] = {
        .mnemonic = "ROR",
        .full_mnemonic = "ROR   d+X",
        .handler = ror_direct_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0x7c] = {0},
    [0x7d] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, X",
        .handler = mov_reg_reg_a_x,
        .length = 0,
        .cycles = 0,
    },
    [0x7e] = {0},
    [0x7f] = {0},
    [0x80] = {
        .mnemonic = "SETC",
        .full_mnemonic = "SETC",
        .handler = setc,
        .length = 0,
        .cycles = 0,
    },
    [0x81] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 8",
        .handler = tcall_8,
        .length = 0,
        .cycles = 0,
    },
    [0x82] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_4_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x83] = {0},
    [0x84] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, d",
        .handler = adc_register_direct_a,
        .length = 0,
        .cycles = 0,
    },
    [0x85] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, !a",
        .handler = adc_register_absolute_a,
        .length = 0,
        .cycles = 0,
    },
    [0x86] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, (X)",
        .handler = adc_register_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x87] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, [d+X]",
        .handler = adc_register_indexed_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x88] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, #i",
        .handler = adc_register_immediate_a,
        .length = 0,
        .cycles = 0,
    },
    [0x89] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   dd, ds",
        .handler = adc_direct_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x8a] = {0},
    [0x8b] = {
        .mnemonic = "DEC",
        .full_mnemonic = "DEC   d",
        .handler = dec_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x8c] = {0},
    [0x8d] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   Y, #i",
        .handler = mov_register_immediate_y,
        .length = 0,
        .cycles = 0,
    },
    [0x8e] = {0},
    [0x8f] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d, #i",
        .handler = mov_direct_immediate,
        .length = 0,
        .cycles = 0,
    },
    [0x90] = {0},
    [0x91] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 9",
        .handler = tcall_9,
        .length = 0,
        .cycles = 0,
    },
    [0x92] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_4_direct,
        .length = 0,
        .cycles = 0,
    },
    [0x93] = {0},
    [0x94] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, d+X",
        .handler = adc_register_direct_indexed_a_x,
        .length = 0,
        .cycles = 0,
    },
    [0x95] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, !a+X",
        .handler = adc_register_absolute_indexed_x,
        .length = 0,
        .cycles = 0,
    },
    [0x96] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, !a+Y",
        .handler = adc_register_absolute_indexed_y,
        .length = 0,
        .cycles = 0,
    },
    [0x97] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   A, [d]+Y",
        .handler = adc_register_indirect_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0x98] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   d, #i",
        .handler = adc_direct_immediate,
        .length = 0,
        .cycles = 0,
    },
    [0x99] = {
        .mnemonic = "ADC",
        .full_mnemonic = "ADC   (X), (Y)",
        .handler = adc_indirect_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0x9a] = {0},
    [0x9b] = {
        .mnemonic = "DEC",
        .full_mnemonic = "DEC   d+X",
        .handler = dec_direct_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0x9c] = {0},
    [0x9d] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, SP",
        .handler = mov_reg_reg_x_sp,
        .length = 0,
        .cycles = 0,
    },
    [0x9e] = {0},
    [0x9f] = {0},
    [0xa0] = {0},
    [0xa1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 10",
        .handler = tcall_10,
        .length = 0,
        .cycles = 0,
    },
    [0xa2] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_5_direct,
        .length = 0,
        .cycles = 0,
    },
    [0xa3] = {0},
    [0xa4] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, d",
        .handler = sbc_register_direct_a,
        .length = 0,
        .cycles = 0,
    },
    [0xa5] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, !a",
        .handler = sbc_register_absolute_a,
        .length = 0,
        .cycles = 0,
    },
    [0xa6] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, (X)",
        .handler = sbc_register_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0xa7] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, [d+X]",
        .handler = sbc_register_indexed_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0xa8] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, #i",
        .handler = sbc_register_immediate_a,
        .length = 0,
        .cycles = 0,
    },
    [0xa9] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   dd, ds",
        .handler = sbc_direct_direct,
        .length = 0,
        .cycles = 0,
    },
    [0xaa] = {0},
    [0xab] = {
        .mnemonic = "INC",
        .full_mnemonic = "INC   d",
        .handler = inc_direct,
        .length = 0,
        .cycles = 0,
    },
    [0xac] = {0},
    [0xad] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   Y, #i",
        .handler = cmp_register_immediate_y,
        .length = 0,
        .cycles = 0,
    },
    [0xae] = {0},
    [0xaf] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   (X)+, A",
        .handler = mov_indirect_incremented_register,
        .length = 0,
        .cycles = 0,
    },
    [0xb0] = {0},
    [0xb1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 11",
        .handler = tcall_11,
        .length = 0,
        .cycles = 0,
    },
    [0xb2] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_5_direct,
        .length = 0,
        .cycles = 0,
    },
    [0xb3] = {0},
    [0xb4] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, d+X",
        .handler = sbc_register_direct_indexed_a_x,
        .length = 0,
        .cycles = 0,
    },
    [0xb5] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, !a+X",
        .handler = sbc_register_absolute_indexed_x,
        .length = 0,
        .cycles = 0,
    },
    [0xb6] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, !a+Y",
        .handler = sbc_register_absolute_indexed_y,
        .length = 0,
        .cycles = 0,
    },
    [0xb7] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   A, [d]+Y",
        .handler = sbc_register_indirect_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0xb8] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   d, #i",
        .handler = sbc_direct_immediate,
        .length = 0,
        .cycles = 0,
    },
    [0xb9] = {
        .mnemonic = "SBC",
        .full_mnemonic = "SBC   (X), (Y)",
        .handler = sbc_indirect_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0xba] = {0},
    [0xbb] = {
        .mnemonic = "INC",
        .full_mnemonic = "INC   d+X",
        .handler = inc_direct_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0xbc] = {0},
    [0xbd] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   SP, X",
        .handler = mov_reg_reg_sp_x,
        .length = 0,
        .cycles = 0,
    },
    [0xbe] = {0},
    [0xbf] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, (X)+",
        .handler = mov_register_indirect_incremented,
        .length = 0,
        .cycles = 0,
    },
    [0xc0] = {0},
    [0xc1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 12",
        .handler = tcall_12,
        .length = 0,
        .cycles = 0,
    },
    [0xc2] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_6_direct,
        .length = 0,
        .cycles = 0,
    },
    [0xc3] = {0},
    [0xc4] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d, a",
        .handler = mov_direct_register_a,
        .length = 0,
        .cycles = 0,
    },
    [0xc5] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   !a, a",
        .handler = mov_absolute_a,
        .length = 0,
        .cycles = 0,
    },
    [0xc6] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   (X), A",
        .handler = mov_indirect_register,
        .length = 0,
        .cycles = 0,
    },
    [0xc7] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   [d+X],A",
        .handler = mov_indexed_indirect_register,
        .length = 0,
        .cycles = 0,
    },
    [0xc8] = {
        .mnemonic = "CMP",
        .full_mnemonic = "CMP   X, #i",
        .handler = cmp_register_immediate_x,
        .length = 0,
        .cycles = 0,
    },
    [0xc9] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   !a, x",
        .handler = mov_absolute_x,
        .length = 0,
        .cycles = 0,
    },
    [0xca] = {0},
    [0xcb] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d, y",
        .handler = mov_direct_register_y,
        .length = 0,
        .cycles = 0,
    },
    [0xcc] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   !a, y",
        .handler = mov_absolute_y,
        .length = 0,
        .cycles = 0,
    },
    [0xcd] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, #i",
        .handler = mov_register_immediate_x,
        .length = 0,
        .cycles = 0,
    },
    [0xce] = {0},
    [0xcf] = {0},
    [0xd0] = {0},
    [0xd1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 13",
        .handler = tcall_13,
        .length = 0,
        .cycles = 0,
    },
    [0xd2] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_6_direct,
        .length = 0,
        .cycles = 0,
    },
    [0xd3] = {0},
    [0xd4] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d+x, a",
        .handler = mov_direct_indexed_register_x_a,
        .length = 0,
        .cycles = 0,
    },
    [0xd5] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   !a+x, A",
        .handler = mov_absolute_indexed_x,
        .length = 0,
        .cycles = 0,
    },
    [0xd6] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   !a+y, A",
        .handler = mov_absolute_indexed_y,
        .length = 0,
        .cycles = 0,
    },
    [0xd7] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   [d]+Y,A",
        .handler = mov_indirect_indexed_register,
        .length = 0,
        .cycles = 0,
    },
    [0xd8] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d, x",
        .handler = mov_direct_register_x,
        .length = 0,
        .cycles = 0,
    },
    [0xd9] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d+y, x",
        .handler = mov_direct_indexed_register_y_x,
        .length = 0,
        .cycles = 0,
    },
    [0xda] = {0},
    [0xdb] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   d+x, y",
        .handler = mov_direct_indexed_register_x_y,
        .length = 0,
        .cycles = 0,
    },
    [0xdc] = {0},
    [0xdd] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, Y",
        .handler = mov_reg_reg_a_y,
        .length = 0,
        .cycles = 0,
    },
    [0xde] = {0},
    [0xdf] = {0},
    [0xe0] = {
        .mnemonic = "CLRV",
        .full_mnemonic = "CLRV",
        .handler = clrv,
        .length = 0,
        .cycles = 0,
    },
    [0xe1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 14",
        .handler = tcall_14,
        .length = 0,
        .cycles = 0,
    },
    [0xe2] = {
        .mnemonic = "SET1",
        .full_mnemonic = "SET1  d",
        .handler = set1_7_direct,
        .length = 0,
        .cycles = 0,
    },
    [0xe3] = {0},
    [0xe4] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, d",
        .handler = mov_register_direct_a,
        .length = 0,
        .cycles = 0,
    },
    [0xe5] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, !a",
        .handler = mov_register_absolute_a,
        .length = 0,
        .cycles = 0,
    },
    [0xe6] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, (X)",
        .handler = mov_register_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0xe7] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, [d+X]",
        .handler = mov_register_indexed_indirect,
        .length = 0,
        .cycles = 0,
    },
    [0xe8] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, #i",
        .handler = mov_register_immediate_a,
        .length = 0,
        .cycles = 0,
    },
    [0xe9] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, !a",
        .handler = mov_register_absolute_x,
        .length = 0,
        .cycles = 0,
    },
    [0xea] = {
        .mnemonic = "NOT1",
        .full_mnemonic = "NOT1  m.b",
        .handler = not1,
        .length = 0,
        .cycles = 0,
    },
    [0xeb] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   Y, d",
        .handler = mov_register_direct_y,
        .length = 0,
        .cycles = 0,
    },
    [0xec] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   Y, !a",
        .handler = mov_register_absolute_y,
        .length = 0,
        .cycles = 0,
    },
    [0xed] = {0},
    [0xee] = {0},
    [0xef] = {0},
    [0xf0] = {0},
    [0xf1] = {
        .mnemonic = "TCALL",
        .full_mnemonic = "TCALL 15",
        .handler = tcall_15,
        .length = 0,
        .cycles = 0,
    },
    [0xf2] = {
        .mnemonic = "CLR1",
        .full_mnemonic = "CLR1  d",
        .handler = clr1_7_direct,
        .length = 0,
        .cycles = 0,
    },
    [0xf3] = {0},
    [0xf4] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, d+X",
        .handler = mov_register_direct_indexed_a_x,
        .length = 0,
        .cycles = 0,
    },
    [0xf5] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, !a+X",
        .handler = mov_register_absolute_indexed_x,
        .length = 0,
        .cycles = 0,
    },
    [0xf6] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, !a+Y",
        .handler = mov_register_absolute_indexed_y,
        .length = 0,
        .cycles = 0,
    },
    [0xf7] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   A, [d]+Y",
        .handler = mov_register_indirect_indexed,
        .length = 0,
        .cycles = 0,
    },
    [0xf8] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, d",
        .handler = mov_register_direct_x,
        .length = 0,
        .cycles = 0,
    },
    [0xf9] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   X, d+Y",
        .handler = mov_register_direct_indexed_x_y,
        .length = 0,
        .cycles = 0,
    },
    [0xfa] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   dd, ds",
        .handler = mov_direct_direct,
        .length = 0,
        .cycles = 0,
    },
    [0xfb] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   Y, d+X",
        .handler = mov_register_direct_indexed_y_x,
        .length = 0,
        .cycles = 0,
    },
    [0xfc] = {0},
    [0xfd] = {
        .mnemonic = "MOV",
        .full_mnemonic = "MOV   Y, A",
        .handler = mov_reg_reg_y_a,
        .length = 0,
        .cycles = 0,
    },
    [0xfe] = {0},
    [0xff] = {0},
};
